### ISSUE TITLE
bot's tank can see through terrain and walls

### ISSUE THREAD

**Issue by kbetmp001** [Joe91/fun-bots#222]
### Scope

Vehicle bot behavior

### What happened?

on map Armored Shield, bots tank keeps stopped and shooting even enemy not in the view. for example, 2 tanks keep shooting each other on point D, through the village, in the whole round. some other tanks stopped on the ramp and shooting on the ground.

### What was expected?

keep moving, shoot when on sight

### How can we reproduce and test it?

load map Armored Shield, game mode conquest, wait bot's tank on position. turn USE_COLLITION_RAYCASTS off can solve this problem.

### Version of fun-bots and VU?

V2.5.3 , VU Build 18476

### I have checked the following... (if applicable)

- [X] I have read the [contribution guidelines on reporting bugs](https://github.com/Joe91/fun-bots/blob/master/.github/CONTRIBUTING.md#reporting-a-bug) and the [code of conduct](https://github.com/Joe91/fun-bots/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have tested and reproduced this bug without any other mods besides fun-bots.

**Comment by FlashHit** [comment]
I think this depends on materialflags which are currently broken if I am not wrong.

**Comment by Joe91** [comment]
There was a bug that kept bots in vehicles shooting forever.
This bug is fixed on the latest dev-commit. You can try if that was this issue...

**Comment by Firjens** [comment]
Is this issue resolved? @kbetmp001

**Comment by aliakseiz** [comment]
The issue is still reproducible with fun-bots `v2.6.1` and VU build `19412`.
Tested on different maps (i.e. Caspian border, Gulf of Oman), tanks and APCs stand still and keep shooting forever, until the acquired target dies. Regardless of the target visibility.

**Comment by aliakseiz** [comment]
Not reproducible in `v2.7.0-dev3`.
